### ISSUE TITLE
python3 install -e . error

### ISSUE THREAD

**Issue by CAI23sbP** [leekwoon/hrl-nav#2]
안녕하세요. 현재 제공하신 코드와 논문을 인상 깊게 본 학생입니다.
다름이 아니라 제공하신 코드를 설치하는 와중에 에러가 발생하여 문의를 남깁니다.
`pyrangelibc-danieldugas을` 설치하는 도중에 아래와 같이 compiliing error 가 발생했습니다.

 Error compiling Cython file:
  ------------------------------------------------------------
  ...
                      for x in range(width):
                          self.thisptr.grid[x][y] = <bool>arg1[y,x]
              else:
                  self.thisptr = new OMap(arg1)
          else:
              print "Failed to construct PyOMap, check argument types."

현재 저의 환경은 저자께서 설정하신 python 3.6이며,  ubuntu는 18.04로 melodic 입니다.

저자께서 docs에 남겨주신데로 pip3 가 아닌 pip 로 설치하게 되면 pandas==1.1.0: version issue (distribution is not exist) 가 발생합니다. pandas 뿐만 아니라PyQt5, opencv-python==4.6.0.66, 또한 동일한 문제가 발생합니다.
이에 대해서 답변을 주시면 감사하겠습니다.

**Comment by leekwoon** [comment]
안녕하세요. 혹시 [nav-gym](https://github.com/leekwoon/nav-gym)도 설치를 하셨을까요?
nav-gym README에 virtualenv 환경을 참고해서 설치 진행을 추천드립니다.

그리고 `pyrangelibc-danieldugas` 를 직접 설치할때도 에러가 에러가 발생하시나요?
```
pip install pyrangelibc-danieldugas
```

**Comment by CAI23sbP** [comment]
빠른 답변 감사합니다. 
네 가상 환경을 리부트 하고 먼저 [nav-gym](https://github.com/leekwoon/nav-gym)을 설치하기 위해 직접
 `pip install pyrangelibc-danieldugas` 
했을 때 마찬가지로 동일한 오류가 나옵니다.

**Comment by CAI23sbP** [comment]
@leekwoon  안녕하세요 해당 문제를 해결했습니다.
[range_libc](https://github.com/kctess5/range_libc)  홈페이지에 접속하여 PythonWrappers에 따라 진행하되 `print "Failed to construct PyOMap, check argument types."` 와 같이 해당 문제 부분을 전부 찾아` print ("Failed to construct PyOMap, check argument types.")` 으로 변경하여 설치를 진행하니 최종적으로 저자께서 제공하신 코드가 돌아가는 것을 확인했습니다.

Hi, guys.
If you have a problem which installs a range_libc.
I recommend to visit this `[site](https://github.com/kctess5/range_libc)`.
And following 'PythonWrappers' ,but you must change codes in some files.
When you have done, you can test this awesome DRL code

**Comment by 1213142332** [comment]
I also encountered the same problem, how can I solve it?

**Comment by CAI23sbP** [comment]
@1213142332 
How are you? Just changing some files which fit in python2.x to python3.x
